language: java
jdk:
  - oraclejdk7
script: mvn clean verify -DskipTests=true


after_success:
  - openssl aes-256-cbc -pass pass:${env.ENCRYPTION_PASSWORD} -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:${env.ENCRYPTION_PASSWORD} -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers><profiles><id>ossrh</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.executable>gpg</gpg.executable><gpg.passphrase>\${env.GPGPASSPHRASE}</gpg.passphrase><properties></settings>" > ~/settings.xml                                                                                                                              <profile>
  - mvn clean deploy -DperformRelease=true --settings ~/settings.xml

env:
  global:
  - GPG_DIR="`pwd`/deploy"