language: java
sudo: required
jdk:
  - oraclejdk7
script: sudo mvn clean verify

after_success:
  - sudo echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - sudo mvn deploy -DperformRelease=true --settings ~/settings.xml